services:
  searxng:
    image: docker.io/searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: 'json-file'
      options:
        max-size: '1m'
        max-file: '1'
    networks:
      - default

  justask-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - searxng
    networks:
      - default

  justask-ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - justask-backend
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - default
