version: '3.8'
services:
  searxng:
    build:
      context: ./metasearch-engines
      dockerfile: Dockerfile
    environment:
      - BASE_URL=http://localhost:8080
      - INSTANCE_NAME=just-ask
    ports:
      - 8080:8080
    volumes:
      - ./metasearch-engines/searxng:/etc/searxng
    networks:
      - default

  metasearch-engine:
    build:
      context: ./metasearch-api
      dockerfile: Dockerfile
    depends_on:
      - searxng
    networks:
      - default

  just-ask:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - metasearch-engine
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - default
